language: bash

env:
  global:
  - IMAGE_NAME=${DOCKER_USERNAME}/jupyter-pyspark-toree

matrix:
  include:
  - services: docker
    env:
    - SPARK_VERSION=2.1.3
    - PYTHON_MAJOR_VERSION=2
  - services: docker
    env:
    - SPARK_VERSION=2.1.3
    - PYTHON_MAJOR_VERSION=3
  - services: docker
    env:
    - SPARK_VERSION=2.2.2
    - PYTHON_MAJOR_VERSION=2
  - services: docker
    env:
    - SPARK_VERSION=2.2.2
    - PYTHON_MAJOR_VERSION=3
  - services: docker
    env:
    - SPARK_VERSION=2.3.2
    - PYTHON_MAJOR_VERSION=2
  - services: docker
    env:
    - SPARK_VERSION=2.3.2
    - PYTHON_MAJOR_VERSION=3
  
before_script:
- set -e
- docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

script:
- TAG_NAME="spark-${SPARK_VERSION}_python-${PYTHON_MAJOR_VERSION}"
- FULL_IMAGE_NAME="${IMAGE_NAME}:${TAG_NAME}"
- |
  docker build . \
    --build-arg SPARK_VERSION="${SPARK_VERSION}" \
    --build-arg PYTHON_MAJOR_VERSION="${PYTHON_MAJOR_VERSION}" \
    -t ${FULL_IMAGE_NAME}

after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker push ${FULL_IMAGE_NAME};
  fi

branches:
  only:
  - master
